Repository hmcts/finrem-ccd-definitions, pull requests merged in 2021-10, with the labels that each got.

#527 Update dependencies
  package.json
  test/data/ccd-consented-basic-data.json
  test/data/ccd-contested-basic-data.json
  test/data/ccd-hwf-consented-payment.json
  test/data/ccd-hwf-contested-payment.json
  test/data/verify-consented-tab-data.json
  test/functional/consented_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-527

#531 DFR-597 - Fix nightly pipeline
  test/functional/pages/create-case/create-case.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-531

#529 DFR-105 Add Judges
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-529
