Repository hmcts/finrem-ccd-definitions, pull requests merged in 2021-05, with the labels that each got.

#459 Increase wait time for intermittent failures on cross browser.
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  test/functional/pages/check-your-answers/check-your-answers.js
  test/functional/pages/divorce-details/divorce-details.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-459

#461 RPET-980: removed permissions from caa idam role
  definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
  test/unit/definitions/consented/UserRoleStateAuth.test.js
  test/unit/definitions/contested/UserRoleStateAuth.test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-461

#462 Revert "RPET-980: removed permissions from caa idam role "
  definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
  test/unit/definitions/consented/UserRoleStateAuth.test.js
  test/unit/definitions/contested/UserRoleStateAuth.test.js
  yarn-audit-known-issues
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-462

#460 RPET-944: Update Judge List and add Display Ordering
  Jenkinsfile_CNP
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-460

#466 RPET-992: Update state permissions for CAA and solicitor roles
  README.md
  definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
  test/unit/definitions/consented/UserEventAuthorisation.test.js
  test/unit/definitions/consented/UserRoleStateAuth.test.js
  test/unit/definitions/contested/UserRoleStateAuth.test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-466

#467 share a case after Issue event, RPET-992
  test/functional/contested-respondent_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-467

#472 Update readme
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-472

#469 fix cross browser issues
  bin/run-crossbrowser-tests.sh
  test/crossbrowser/supportedBrowsers.js
  test/functional/contested_test.js
  test/functional/pages/amend-application-details/amend-application-details.js
  test/functional/pages/check-your-answers/check-your-answers.js
  test/functional/pages/share-case-in-org/share-case-in-org.js
  test/functional/saucelabs.conf.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-469
