Repository hmcts/finrem-ccd-definitions, pull requests merged in 2021-09, with the labels that each got.

#522 Remove comma from Jenkinsfile_CNP config
  Jenkinsfile_CNP
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-522

#521 DFR-569 - Fixing Nightly pipeline
  bin/run-crossbrowser-tests.sh
  test/crossbrowser/supportedBrowsers.js
  test/functional/consented_test.js
  test/functional/contested-respondent_test.js
  test/functional/contested_test.js
  test/functional/pages/amend-application-details/amend-application-details.js
  test/functional/pages/applicant-details/applicant-details.js
  test/functional/pages/case-authorisation/case-authorisation.js
  test/functional/pages/check-your-answers/check-your-answers.js
  test/functional/pages/consent-order/consent-order.js
  test/functional/pages/contested-pages/apply-court.js
  test/functional/pages/contested-pages/complexity-list.js
  test/functional/pages/contested-pages/fast-track.js
  test/functional/pages/contested-pages/mediation-questions.js
  test/functional/pages/create-case/create-case.js
  test/functional/pages/d81-question/d81-question.js
  test/functional/pages/divorce-details/divorce-details.js
  test/functional/pages/final-payment-submission-page/final-payment-submission-page.js
  test/functional/pages/hwf-payment-details/hwf-payment-detail.js
  test/functional/pages/nature-of-application/nature-of-application.js
  test/functional/pages/optional-documents/optional-documents.js
  test/functional/pages/order-for-children/order-for-children.js
  test/functional/pages/org-assign-cases/org-assign-cases-to-respondent.js
  test/functional/pages/payment-page/payment-page.js
  test/functional/pages/payment-submission/payment-submisison.js
  test/functional/pages/respondent-details/respondent-details.js
  test/functional/pages/saving-application-information/saving-application-information.js
  test/functional/pages/share-case-in-org/share-case-in-org.js
  test/functional/pages/solicitor-create/solicitor-create.js
  test/functional/pages/tab-data-verification/tab-data-verification.js
  test/functional/saucelabs.conf.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-521

#525 DFR-435: Fees increases
  definitions/consented/json/CaseTypeTab/CaseTypeTab.json
  test/data/verify-contested-tab-data.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-525
