Repository hmcts/finrem-ccd-definitions, pull requests merged in 2021-03, with the labels that each got.

#421 Point AAT at AAT pod
  package.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-421

#422 revert rpet 704
  Jenkinsfile_CNP
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-422

#424 Add new keys for consented and contested fixed list.
  Jenkinsfile_CNP
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-424

#423 Enable share respondent nightly test
  Jenkinsfile_nightly
  test/functional/contested-respondent_test.js
  test/functional/pages/org-assign-cases/org-assign-cases-to-respondent.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-423

#425 add missing keys to nightly pipeline
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-425

#427 Leave IDAM solicitor permissions on case states to support legacy cases
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState-respSol-nonprod.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-427

#429 Revert secret to previous release
  Jenkinsfile_CNP
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-429

#434 FR Respondent Solicitor Release
  definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent-respSol-nonprod.json
  definitions/consented/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField-respSol-nonprod.json
  definitions/consented/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState-respSol-nonprod.json
  definitions/consented/json/AuthorisationCaseType/AuthorisationCaseType-respSol-nonprod.json
  definitions/consented/json/AuthorisationComplexType/AuthorisationComplexType-respSol-nonprod.json
  definitions/consented/json/CaseEvent/CaseEvent-respSol-nonprod.json
  definitions/consented/json/CaseEvent/CaseEvent.json
  definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes-respSolJourney-nonprod.json
  definitions/consented/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
  definitions/consented/json/CaseEventToFields/CaseEventToFields-respSol-nonprod.json
  definitions/consented/json/CaseEventToFields/CaseEventToFields.json
  definitions/consented/json/CaseTypeTab/CaseTypeTab-respSolJourney-nonprod.json
  definitions/consented/json/CaseTypeTab/CaseTypeTab.json
  definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-respSol-nonprod.json
  definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent-respSol-prod.json
  definitions/contested/json/AuthorisationCaseEvent/AuthorisationCaseEvent.json
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField-respSol-nonprod.json
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState-respSol-nonprod.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState-respSol-prod.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
  definitions/contested/json/AuthorisationCaseType/AuthorisationCaseType-respSol-nonprod.json
  definitions/contested/json/AuthorisationCaseType/AuthorisationCaseType.json
  definitions/contested/json/AuthorisationComplexType/AuthorisationComplexType-respSol-nonprod.json
  definitions/contested/json/CaseEvent/CaseEvent-respSol-nonprod.json
  definitions/contested/json/CaseEvent/CaseEvent.json
  definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes-respSolJourney-nonprod.json
  definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields-respSolJourney-nonprod.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields.json
  definitions/contested/json/CaseField/CaseField-respSolJourney-nonprod.json
  definitions/contested/json/CaseField/CaseField.json
  definitions/contested/json/CaseTypeTab/CaseTypeTab-respSol-nonprod.json
  definitions/contested/json/CaseTypeTab/CaseTypeTab.json
  definitions/contested/json/ComplexTypes/ComplexTypes-respSol-nonprod.json
  definitions/contested/json/ComplexTypes/ComplexTypes.json
  test/unit/definitions/consented/UserRoleStateAuth.test.js
  test/unit/definitions/contested/CaseEventToFields.test.js
  test/unit/definitions/contested/CaseTypeTab.test.js
  test/unit/definitions/contested/UserEventAuthorisation.test.js
  test/unit/definitions/contested/UserRoleStateAuth.test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-434

#439 Updated generate-all to include ITHC and PerfTest config
  README.md
  package.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-439

#441 test-accessibility
  .eslintignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  test/accessibility/runner.js
  test/functional/codecept.conf.js
  test/functional/consented_test.js
  test/functional/contested_test.js
  test/functional/pages/applicant-details/applicant-details.js
  test/functional/pages/case-authorisation/case-authorisation.js
  test/functional/pages/check-your-answers/check-your-answers.js
  test/functional/pages/consent-order/consent-order.js
  test/functional/pages/create-case/create-case.js
  test/functional/pages/divorce-details/divorce-details.js
  test/functional/pages/final-payment-submission-page/final-payment-submission-page.js
  test/functional/pages/hwf-payment-details/hwf-payment-detail.js
  test/functional/pages/nature-of-application/nature-of-application.js
  test/functional/pages/optional-documents/optional-documents.js
  test/functional/pages/order-for-children/order-for-children.js
  test/functional/pages/payment-page/payment-page.js
  test/functional/pages/payment-submission/payment-submisison.js
  test/functional/pages/respondent-details/respondent-details.js
  test/functional/pages/saving-application-information/saving-application-information.js
  test/functional/pages/solicitor-create/solicitor-create.js
  test/helpers/PuppeteerHelper.js
  test/reporter/Report.html
  test/reporter/customReporter.js
  test/reporter/resources/angular.min.js
  test/reporter/resources/css/all.css
  test/reporter/resources/webfonts/fa-solid-900.woff2
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-441
