Repository hmcts/finrem-ccd-definitions, pull requests merged in 2025-06, with the labels that each got.

#2588 DFR-3823: Add PW test for Manage Case Documents & deletion of codecept test
  playwright-e2e/config/case-data.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/consented/case_flag_tests.spec.ts
  playwright-e2e/functional/contested/FR_manageCaseDocuments/manage_case_documents.spec.ts
  playwright-e2e/pages/events/manage-case-documents/ManageCaseDocumentsPage.ts
  test/functional/contested_events_test.js
  test/functional/pages/manage-confidential-documents/manage-confidential-documents.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2588

#2589 Renamed to propertyAdjustmentOrderDetailLabel
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields-newPaperCase.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields.json
  definitions/contested/json/CaseField/CaseField.json
  definitions/contested/json/CaseTypeTab/CaseTypeTab.json
  src/test/java/finrem/cfv/CategoriesToReassign.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2589

#2605 DFR-3842 Fix test to stop at api failures, fix date format, clean up codecept
  playwright-e2e/functional/helpers/ApiBuilder.ts
  playwright-e2e/functional/helpers/DateHelper.ts
  test/functional/consented_caseflag_test.js
  test/functional/steps_file.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2605

#2609 Fix CVE brace-expansion
  package.json
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2609

#2595 DFR-3788: Handle PBA payment errors
  definitions/consented/json/CaseEvent/CaseEvent.json
  definitions/contested/json/CaseEvent/CaseEvent.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/data/payload/consented/caseworker/issue-application.json
  playwright-e2e/data/payload/consented/solicitor/case-submission.json
  playwright-e2e/functional/consented/application_payment_submission.spec.ts
  playwright-e2e/functional/contested/application_payment_submission.spec.ts
  playwright-e2e/functional/helpers/Consented/ConsentedPayloadHelper.ts
  test/functional/pages/pba-payment/pba-payment.js
Labels: ns:financial-remedy, prd:finrem, use-finrem-cos-pr-2329, rel:finrem-ccd-definitions-pr-2595

#2599 DFR-3837 - CT: Typo in Manage case documents page
  definitions/contested/json/ComplexTypes/ComplexTypes.json
  playwright-e2e/pages/events/manage-case-documents/ManageCaseDocumentsPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2599

#2610 DFR-3851 PW- Add Note event, Fix Nightly test failures, refactor tests
  playwright-e2e/config/case-data.ts
  playwright-e2e/data/tab_content/common-tabs/notes_tabs.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/contested/FR_ManageHearings/manage_hearings.spec.ts
  playwright-e2e/functional/contested/FR_addNote/addNote.spec.ts
  playwright-e2e/functional/helpers/ApiBuilder.ts
  playwright-e2e/functional/helpers/Contested/ContestedCaseDataHelper.ts
  playwright-e2e/functional/helpers/DateHelper.ts
  playwright-e2e/functional/helpers/PayloadMutator.ts
  playwright-e2e/pages/BaseJourneyPage.ts
  playwright-e2e/pages/CaseDetailsPage.ts
  playwright-e2e/pages/events/add-note/AddNotePage.ts
  playwright-e2e/pages/events/create-case/DivorceDetailsPage.ts
  playwright-e2e/pages/events/manage-hearings/ManageHearing.ts
  test/functional/contested_events_test.js
  test/functional/pages/add-note/add-note.js
  test/functional/steps_file.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2610

#2613 Dfr 3738 mange hearing tab
  definitions/contested/json/AuthorisationCaseField/ManageHearings-nonprod.json
  definitions/contested/json/AuthorisationComplexType/ManageHearings-nonprod.json
  definitions/contested/json/CaseField/ManageHearings-nonprod.json
  definitions/contested/json/CaseTypeTab/ManageHearings-nonprod.json
  definitions/contested/json/ComplexTypes/ManageHearings-nonprod.json
Labels: ns:financial-remedy, prd:finrem, use-finrem-cos-pr-2345, rel:finrem-ccd-definitions-pr-2613

#2616 quick fix for nightly assert tab failures in case flag tests
  playwright-e2e/pages/CaseDetailsPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2616

#2630 DFR-3853 Enable PW reporting feature
  Jenkinsfile_nightly
  package.json
  playwright.config.ts
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2630

#2629 DFR-3852_2 Adding update contact details and change in representation flow
  playwright-e2e/pages/events/update-contact-details/UpdateContactDetailsPage.ts
  playwright-e2e/resources/check_your_answer_content/update_contact_details/updateContactDetailsTable.ts
  playwright-e2e/resources/tab_content/consented/update_contact_details_not_represented.ts
  playwright-e2e/resources/tab_content/consented/update_contact_details_represented.ts
  playwright-e2e/test/consented/update_contact_details.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2629

#2637 DFR-3829: Added allocate to judge UI validation to give_allocation_di…
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/events/allocate-to-judge/AllocateToJudgePage.ts
  playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2637

#2646 DFR-3886 Refund Page and Event Summary page
  playwright-e2e/config/case-data.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/events/EventSummaryPage.ts
  playwright-e2e/pages/events/add-note/AddNotePage.ts
  playwright-e2e/pages/events/refund/RefundPage.ts
  playwright-e2e/test/contested/FR_addNote/addNote.spec.ts
  playwright-e2e/test/contested/createFlags/case_flag_tests.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2646

#2642 Dfr-3866 Contested Update Contact Details - Change in Representation
  playwright-e2e/pages/events/update-contact-details/UpdateContactDetailsPage.ts
  playwright-e2e/resources/check_your_answer_content/update_contact_details/updateContactDetailsTable.ts
  playwright-e2e/resources/tab_content/contested/update_contact_details_not_represented.ts
  playwright-e2e/resources/tab_content/contested/update_contact_details_represented.ts
  playwright-e2e/test/contested/FR_updateContactDetails/contested_update_contact_details.spec.ts
  playwright-e2e/test/contested/FR_updateContactDetails/update_contact_details.spec.ts
  test/functional/contested_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2642
