Repository hmcts/finrem-ccd-definitions, pull requests merged in 2025-08, with the labels that each got.

#2643 DFR-3577-Show-Email-Date-Time-Sent
  definitions/consented/json/ComplexTypes/ComplexTypes.json
  definitions/contested/json/ComplexTypes/ComplexTypes.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/config/config.ts
  playwright-e2e/data-utils/DateHelper.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/CaseDetailsPage.ts
  playwright-e2e/pages/components/tab.ts
  playwright-e2e/pages/events/create-general-email/CreateGeneralEmailPage.ts
  playwright-e2e/resources/check_your_answer_content/create_general_email/createGeneralEmailTable.ts
  playwright-e2e/resources/tab_content/consented/case_documents_tab.ts
  playwright-e2e/resources/tab_content/contested/case_documents_tab.ts
  playwright-e2e/test/common-tests/create_general_email.spec.ts
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2643, use-finrem-cos-pr-2373

#2748 Fix yarn version upgrade failure in nightly pipeline
  package.json
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2748

#2750 Removed Codecept dependencies from package.json
  package.json
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2750

#2751 Fix Nightly test failures
  playwright-e2e/pages/CaseDetailsPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2751

#2759 Refactored generate report to Axe fixtures
  playwright-e2e/fixtures/axe-fixture.ts
  playwright-e2e/fixtures/utils/axe-utils.ts
  playwright-e2e/test/consented/approve_application.spec.ts
  playwright-e2e/test/consented/create_case.spec.ts
  playwright-e2e/test/consented/update_contact_details.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_case.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_express_case.spec.ts
  playwright-e2e/test/contested/FR_GeneralApplicationDirections/general_application_directions.spec.ts
  playwright-e2e/test/contested/FR_ManageHearings/manage_hearings.spec.ts
  playwright-e2e/test/contested/FR_SendOrderToApplicantSolicitor/send_order_applicant_solicitor.spec.ts
  playwright-e2e/test/contested/FR_UploadDraftOrder/upload_draft_order.spec.ts
  playwright-e2e/test/contested/FR_addSchedulingListingInfo/list_for_hearing_express_case.spec.ts
  playwright-e2e/test/contested/FR_amendApplication/amend_form_a_application_details_standard_case.spec.ts
  playwright-e2e/test/contested/FR_consentOrder/consent_in_contested_case.spec.ts
  playwright-e2e/test/contested/FR_directionOrder/process-order.spec.ts
  playwright-e2e/test/contested/FR_generalApplication/general_application_e2e.spec.ts
  playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction.spec.ts
  playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction_express_case.spec.ts
  playwright-e2e/test/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts
  playwright-e2e/test/contested/FR_manageBarrister/manage_barrister.spec.ts
  playwright-e2e/test/contested/FR_manageCaseDocuments/manage_case_documents.spec.ts
  playwright-e2e/test/contested/FR_manageExpressCase/manage_express_case.spec.ts
  playwright-e2e/test/contested/FR_manageInterverners/manage_interveners.spec.ts
  playwright-e2e/test/contested/FR_sendOrder/send_order.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2759

#2760 Fix Accessibility report Not expanding subsections in report
  playwright-e2e/fixtures/utils/axe-utils.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2760

#2712 DFR-3824 Dissociate old draft orders event from Upload approved order event
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/contested/json/CaseEvent/CaseEvent.json
  definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields.json
  definitions/contested/json/CaseField/CaseField.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2712, use-finrem-cos-pr-2416

#2729 DFR-3942 CS & CT: Case creation allows invalid email addresses to be entered
  definitions/contested/json/CaseEventToFields/CaseEventToFields-newPaperCase.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2729, use-finrem-cos-pr-2433

#2767 Fix nightly failure
  playwright-e2e/pages/events/approve-order/ApproveApplicationPage.ts
  playwright-e2e/test/consented/approve_application.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2767

#2762 DFR-3971 CT Upload Approved Order - Migrate exsting hearings to new MH data structure
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/contested/json/CaseEventToFields/CaseEventToFields.json
  definitions/contested/json/CaseField/CaseField.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/events/upload-approved-order/UploadApprovedOrderPage.ts
  playwright-e2e/resources/tab_content/contested/hearings_tabs.ts
  playwright-e2e/test/contested/FR_uploadApprovedOrder/upload_approved_order.spec.ts
Labels: ns:financial-remedy, prd:finrem, use-finrem-cos-pr-2486, rel:finrem-ccd-definitions-pr-2762

#2770 DFR-3991 PW - Extend capability to run test suite in different Env in nightly pipeline
  Jenkinsfile_nightly
  playwright-e2e/config/config.ts
  playwright-e2e/data-utils/api/CaseAssignmentApi.ts
  playwright-e2e/data-utils/api/CcdApi.ts
  playwright-e2e/data-utils/factory/contested/ContestedCaseFactory.ts
  playwright-e2e/data-utils/test_data/EnvTestDataConfig.ts
  playwright-e2e/data-utils/test_data/JsonEnvValReplacer.ts
  playwright-e2e/pages/CaseListPage.ts
  playwright-e2e/pages/SigninPage.ts
  playwright-e2e/resources/case_data/consented/ccd-consented-case-creation.json
  playwright-e2e/resources/case_data/contested/forma/ccd-contested-base.json
  playwright-e2e/resources/case_data/contested/paper_case/ccd-contested-base.json
  playwright-e2e/resources/case_data/contested/paper_case/ccd-contested-refuge-applicant.json
  playwright-e2e/resources/check_your_answer_content/amend_application_details/amendApplicationDetailsTable.ts
  playwright-e2e/resources/check_your_answer_content/case_submission/caseSubmissionTable.ts
  playwright-e2e/resources/check_your_answer_content/create_case/createCaseTable.ts
  playwright-e2e/resources/check_your_answer_content/update_contact_details/updateContactDetailsTable.ts
  playwright-e2e/resources/edited_page_content/contested/applicant-details.ts
  playwright-e2e/resources/payload/contested/caseworker/create-general-application/sender-is-applicant.json
  playwright-e2e/resources/payload/contested/caseworker/list-for-hearing/fda-example-one.json
  playwright-e2e/resources/payload/contested/caseworker/manage-barristers/add-applicant-barrister.json
  playwright-e2e/resources/payload/contested/caseworker/manage-barristers/add-respondent-barrister.json
  playwright-e2e/resources/payload/contested/caseworker/manage-hearing/add-a-hearing/add-a-hearing.json
  playwright-e2e/resources/payload/contested/caseworker/manage-interveners/add-applicant-intervener.json
  playwright-e2e/resources/payload/contested/caseworker/manage-interveners/add-respondent-intervener.json
  playwright-e2e/resources/payload/contested/caseworker/manual-payment.json
  playwright-e2e/resources/payload/contested/caseworker/upload-draft-orders/agreed-draft-orders-applicant.json
  playwright-e2e/resources/payload/contested/solicitor/schedule1-create-case.json
  playwright-e2e/resources/tab_content/consented/create_case_tabs.ts
  playwright-e2e/resources/tab_content/consented/update_contact_details_caseworker_tabs.ts
  playwright-e2e/resources/tab_content/consented/update_contact_details_not_represented.ts
  playwright-e2e/resources/tab_content/consented/update_contact_details_represented.ts
  playwright-e2e/resources/tab_content/contested/caseworker_create_case_tabs.ts
  playwright-e2e/resources/tab_content/contested/contested_update_contact_details_caseworker_tabs.ts
  playwright-e2e/resources/tab_content/contested/draft_orders_tabs.ts
  playwright-e2e/resources/tab_content/contested/respondent_assigned_case_tabs.ts
  playwright-e2e/resources/tab_content/contested/send_order_tab.ts
  playwright-e2e/resources/tab_content/contested/solicitor_amend_case_tabs.ts
  playwright-e2e/resources/tab_content/contested/solicitor_create_case_tabs.ts
  playwright-e2e/resources/tab_content/contested/update_contact_details_not_represented.ts
  playwright-e2e/resources/tab_content/contested/update_contact_details_represented.ts
  playwright-e2e/resources/tab_content/contested/upload_draft_order_tabs.ts
  playwright-e2e/test/consented/application_payment_submission.spec.ts
  playwright-e2e/test/consented/update_contact_details.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_express_papercase.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_papercase.spec.ts
  playwright-e2e/test/contested/FR_amendApplication/amend_form_a_application_details_standard_case.spec.ts
  playwright-e2e/test/contested/FR_consentOrder/consent_in_contested_case.spec.ts
  playwright-e2e/test/contested/application_payment_submission.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2770

#2781 Add missing rename processOrderAddHearing -> isAddHearingChosen
  playwright-e2e/pages/events/process-order/ProcessOrderHearingDetailsPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2781

#2783 DFR-4047 PW test for Notice of Change scenario
  Jenkinsfile_nightly
  playwright-e2e/config/config.ts
  playwright-e2e/data-utils/api/TokenHelperApi.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/NoticeOfChangePage.ts
  playwright-e2e/test/common-tests/notice_of_change.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2783

#2784 Fix PW test which is failing due to Manage Hearing state change
  playwright-e2e/test/contested/FR_addSchedulingListingInfo/list_for_hearing_shows_hearing_tab.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2784
