Repository hmcts/finrem-ccd-definitions, pull requests merged in 2025-05, with the labels that each got.

#2519 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2519

#2512 Dfr 3769 pw create
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/contested/FR_addSchedulingListingInfo/list_for_hearing_shows_hearing_tab.spec.ts
  playwright-e2e/functional/contested/FR_giveAllocationDirections/give_allocation_direction.spec.ts
  playwright-e2e/functional/contested/FR_giveAllocationDirections/give_allocation_direction_express_case.spec.ts
  playwright-e2e/functional/contested/FR_manageExpressCase/manage_express_case.spec.ts
  playwright-e2e/functional/contested/amend_application_details/amend_Form_A_application_details_express_case.spec.ts
  playwright-e2e/functional/helpers/CaseDataHelper.ts
  playwright-e2e/functional/helpers/PayloadHelper.ts
  playwright-e2e/pages/BaseJourneyPage.ts
  playwright-e2e/pages/events/list-for-hearing/ListForHearingPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2512

#2520 Dfr 3770 interim hearings data setup
  playwright-e2e/config/case_events.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts
  playwright-e2e/functional/helpers/PayloadHelper.ts
  playwright-e2e/pages/events/list-for-interim-hearing/ListForInterimHearingPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2520

#2522 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2522

#2511 DFR-3732 reverse changes for superuser access in caseAdded state
  definitions/consented/json/AuthorisationCaseState/AuthorisationCaseState.json
  definitions/contested/json/AuthorisationCaseState/AuthorisationCaseState.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2511

#2506 DFR-3538 Add manage hearing event with Add Hearing action radio
  definitions/contested/json/AuthorisationCaseEvent/ManageHearings-nonprod.json
  definitions/contested/json/AuthorisationCaseField/ManageHearings-nonprod.json
  definitions/contested/json/CaseEvent/ManageHearings-nonprod.json
  definitions/contested/json/CaseEventToFields/ManageHearings-nonprod.json
  definitions/contested/json/CaseField/ManageHearings-nonprod.json
  definitions/contested/json/FixedLists/ManageHearings-nonprod.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2506, use-finrem-cos-pr-2272

#2528 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2528

#2483 DFR-3541 - Intervener solicitors can see applicant or respondent hearing orders in CFV
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/contested/json/CaseField/CaseField.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2483, use-finrem-cos-pr-2249

#2532 Dfr 3771 general applications data
  playwright-e2e/config/case_events.ts
  playwright-e2e/data/payload/contested/caseworker/create-general-application/sender-is-applicant.json
  playwright-e2e/data/payload/contested/caseworker/general-application-directions/old-style-hearing-required-yes.json
  playwright-e2e/data/payload/contested/caseworker/general-application-outcome/outcome-is-other.json
  playwright-e2e/data/payload/contested/caseworker/refer-to-judge/judge-email-is-null.json
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/contested/FR_GeneralApplicationDirections/general_application_directions.spec.ts
  playwright-e2e/functional/helpers/PayloadHelper.ts
  playwright-e2e/pages/events/general-application-directions/GeneralApplicationDirectionsPage.ts
  test/helpers/utils.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2532

#2539 DFR-3670: Add access to field latestDraftHearingOrder for system update role
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2539

#2535 DFR 3784 Manage Flag Consented PW
  playwright-e2e/config/case_events.ts
  playwright-e2e/data/payload/consented/caseworker/create-flag.json
  playwright-e2e/data/tab_content/consented/case_flag_tabs_updated.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/consented/case_flag_tests.spec.ts
  playwright-e2e/functional/helpers/PayloadHelper.ts
  playwright-e2e/pages/CaseDetailsPage.ts
  playwright-e2e/pages/events/manage-flag/ManageFlagPage.ts
  test/functional/consented_caseflag_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2535

#2534 DFR-3780 Remove Jitpack dependency
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2534

#2505 DFR-3476 Set restrictions on document format
  definitions/contested/json/ComplexTypes/ComplexTypes.json
  playwright-e2e/config/case_events.ts
  playwright-e2e/data/payload/contested/paper_case/ccd-contested-base.json
  playwright-e2e/data/test.doc
  playwright-e2e/data/test.docx
  playwright-e2e/data/test.png
  playwright-e2e/data/test.xls
  playwright-e2e/data/test.xlsx
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/contested/restrict_upload_file_format.spec.ts
  playwright-e2e/pages/events/create-general-application/CreateGeneralApplicationPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2505

#2542 DFR-3670: Add access to orderApprovedCoverLetter for system role
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2542

#2544 bump befta and remove jitpack
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2544

#2550 Fix failing codecept test
  test/functional/contested_events_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2550

#2533 DFR-3647 add new hearing
  definitions/contested/json/AuthorisationCaseField/ManageHearings-nonprod.json
  definitions/contested/json/CaseEvent/ManageHearings-nonprod.json
  definitions/contested/json/CaseEventToFields/ManageHearings-nonprod.json
  definitions/contested/json/CaseField/ManageHearings-nonprod.json
  definitions/contested/json/ComplexTypes/ManageHearings-nonprod.json
  definitions/contested/json/FixedLists/ManageHearings-nonprod.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, use-finrem-cos-pr-2285, rel:finrem-ccd-definitions-pr-2533

#2554 Dfr 3772 test hearing from process order
  .gitignore
  package.json
  playwright-e2e/config/case_events.ts
  playwright-e2e/data/payload/contested/caseworker/list-for-hearing/fda-example-one.json
  playwright-e2e/data/payload/contested/caseworker/process-order/basic-two-hearing.json
  playwright-e2e/data/payload/contested/judiciary/most-basic-approve-orders.json
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/functional/contested/FR_GeneralApplicationDirections/general_application_directions.spec.ts
  playwright-e2e/functional/contested/FR_addSchedulingListingInfo/list_for_hearing_express_case.spec.ts
  playwright-e2e/functional/contested/FR_addSchedulingListingInfo/list_for_hearing_shows_hearing_tab.spec.ts
  playwright-e2e/functional/contested/FR_directionOrder/process-order-spec.ts
  playwright-e2e/functional/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts
  playwright-e2e/functional/helpers/DateHelper.ts
  playwright-e2e/functional/helpers/DocumentHelper.ts
  playwright-e2e/functional/helpers/PayloadHelper.ts
  playwright-e2e/pages/BaseJourneyPage.ts
  playwright-e2e/pages/events/list-for-interim-hearing/ListForInterimHearingPage.ts
  playwright-e2e/pages/events/upload-draft-orders/UploadDraftOrdersPage.ts
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2554

#2538 DFR-3792 CT Intervener representative email input permits invalid ema…
  definitions/contested/json/ComplexTypes/ComplexTypes.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2538

#2547 DFR-3801: Flag event as read-only
  definitions/contested/json/CaseEvent/CaseEvent.json
Labels: ns:financial-remedy, prd:finrem, use-finrem-cos-pr-2306, rel:finrem-ccd-definitions-pr-2547

#2555 DFR-3791 CS: Paper case Send Order fails if case has no court
  definitions/consented/json/CaseEvent/CaseEvent.json
Labels: ns:financial-remedy, prd:finrem, use-finrem-cos-pr-2296, rel:finrem-ccd-definitions-pr-2555

#2552 Dfr 3522 case creation api playwright
  package.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/config/case_events.ts
  playwright-e2e/data/payload/contested/caseworker/HWF-payment.json
  playwright-e2e/data/tab_content/contested/respondent_assigned_case_tabs.ts
  playwright-e2e/fixtures/fixtures.ts
  playwright-e2e/functional/consented/application_payment_submission.spec.ts
  playwright-e2e/functional/consented/approve_application.spec.ts
  playwright-e2e/functional/consented/case_flag_tests.spec.ts
  playwright-e2e/functional/consented/hwf_application_accepted.spec.ts
  playwright-e2e/functional/consented/issue_application.spec.ts
  playwright-e2e/functional/consented/update_contact_details.spec.ts
  playwright-e2e/functional/contested/FR_GeneralApplicationDirections/general_application_directions.spec.ts
  playwright-e2e/functional/contested/FR_addSchedulingListingInfo/list_for_hearing_express_case.spec.ts
  playwright-e2e/functional/contested/FR_addSchedulingListingInfo/list_for_hearing_shows_hearing_tab.spec.ts
  playwright-e2e/functional/contested/FR_directionOrder/process-order-spec.ts
  playwright-e2e/functional/contested/FR_giveAllocationDirections/give_allocation_direction.spec.ts
  playwright-e2e/functional/contested/FR_giveAllocationDirections/give_allocation_direction_express_case.spec.ts
  playwright-e2e/functional/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts
  playwright-e2e/functional/contested/FR_manageExpressCase/manage_express_case.spec.ts
  playwright-e2e/functional/contested/amend_application_details/amend_Form_A_application_details_express_case.spec.ts
  playwright-e2e/functional/contested/amend_application_details/amend_paper_application_into_express_pilot.spec.ts
  playwright-e2e/functional/contested/applicant_refuge_status_visibility.spec.ts
  playwright-e2e/functional/contested/application_payment_submission.spec.ts
  playwright-e2e/functional/contested/assign_respondent_case.spec.ts
  playwright-e2e/functional/contested/create_case/create_case.spec.ts
  playwright-e2e/functional/contested/restrict_upload_file_format.spec.ts
  playwright-e2e/functional/e2e.spec.ts
  playwright-e2e/functional/helpers/ApiBuilder.ts
  playwright-e2e/functional/helpers/CaseDataBuilder.ts
  playwright-e2e/functional/helpers/CaseDataHelper.ts
  playwright-e2e/functional/helpers/Consented/ConsentedCaseDataHelper.ts
  playwright-e2e/functional/helpers/Consented/ConsentedPayloadHelper.ts
  playwright-e2e/functional/helpers/Contested/ContestedCaseDataHelper.ts
  playwright-e2e/functional/helpers/Contested/ContestedPayloadHelper.ts
  playwright-e2e/functional/helpers/DateHelper.ts
  playwright-e2e/functional/helpers/PayloadHelper.ts
  playwright-e2e/functional/helpers/PayloadMutator.ts
  playwright-e2e/pages/CaseDetailsPage.ts
  playwright-e2e/pages/events/list-for-interim-hearing/ListForInterimHearingPage.ts
  playwright-e2e/preview/preview.spec.ts
  playwright-e2e/types/replacement-action.ts
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2552

#2562 DFR-3810 Draft orders tab should show when the value is Yes for the judge
  definitions/contested/json/CaseTypeTab/CaseTypeTab.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2562

#2572 DFR-3808 - PW Add Judge create flag case
  playwright-e2e/functional/consented/case_flag_tests.spec.ts
  test/functional/consented_caseflag_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2572

#2573 DFR-3807 Consent Judge manage flag and contest create flag
  playwright-e2e/config/case-data.ts
  playwright-e2e/functional/consented/case_flag_tests.spec.ts
  playwright-e2e/functional/contested/case_flag/case_flag_tests.spec.ts
  test/functional/consented_caseflag_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2573

#2578 Change Nightlies to run at 18:00PM
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2578
