Repository hmcts/finrem-ccd-definitions, pull requests merged in 2025-10, with the labels that each got.

#2866 Replace static docs used in API calls with new ones post doc clean up
  playwright-e2e/data-utils/test_data/EnvTestDataConfig.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2866

#2830 DFR-3983: Add barrister userid
  definitions/contested/json/AuthorisationCaseField/AuthorisationCaseField.json
  definitions/contested/json/ComplexTypes/ComplexTypes.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, use-finrem-cos-pr-2567, rel:finrem-ccd-definitions-pr-2830

#2841 Add GitHub Action to create preview env PRs
  .github/workflows/create-preview-environment.yml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2841

#2878 Fix GitHub Action preview links formatting
  .github/workflows/create-preview-environment.yml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2878

#2882 Update readme with instructions on Create preview environment action
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2882
