Repository hmcts/finrem-ccd-definitions, pull requests merged in 2025-07, with the labels that each got.

#2652 DFR-3892 PW Test - Contested Schedule 1 Case Creation by caseworker
  playwright-e2e/config/config.ts
  playwright-e2e/data-utils/factory/contested/ContestedCaseFactory.ts
  playwright-e2e/pages/BaseJourneyPage.ts
  playwright-e2e/pages/SigninPage.ts
  playwright-e2e/pages/events/create-case/ApplicantDetailsPage.ts
  playwright-e2e/pages/events/create-case/DivorceDetailsPage.ts
  playwright-e2e/pages/events/create-case/NatureOfApplicationPage.ts
  playwright-e2e/pages/events/create-case/RespondentRepresentedPage.ts
  playwright-e2e/pages/events/create-case/SolicitorDetailsPage.ts
  playwright-e2e/pages/events/create-case/UploadOrderDocumentPage.ts
  playwright-e2e/pages/helpers/CaseAssignmentHelper.ts
  playwright-e2e/pages/helpers/CommonActionsHelper.ts
  playwright-e2e/resources/check_your_answer_content/create_case/createCaseTable.ts
  playwright-e2e/resources/tab_content/consented/create_case_tabs.ts
  playwright-e2e/resources/tab_content/contested/caseworker_create_case_tabs.ts
  playwright-e2e/test/CommonTests/add_note.spec.ts
  playwright-e2e/test/consented/addNote.spec.ts
  playwright-e2e/test/consented/application_payment_submission.spec.ts
  playwright-e2e/test/consented/approve_application.spec.ts
  playwright-e2e/test/consented/case_flag_tests.spec.ts
  playwright-e2e/test/consented/create_case.spec.ts
  playwright-e2e/test/consented/hwf_application_accepted.spec.ts
  playwright-e2e/test/consented/issue_application.spec.ts
  playwright-e2e/test/consented/update_contact_details.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_case.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_express_case.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_express_papercase.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_papercase.spec.ts
  playwright-e2e/test/contested/FR_ManageHearings/manage_hearings.spec.ts
  playwright-e2e/test/contested/FR_addNote/addNote.spec.ts
  playwright-e2e/test/contested/FR_addSchedulingListingInfo/list_for_hearing_express_case.spec.ts
  playwright-e2e/test/contested/FR_amendApplication/amend_form_a_application_details_standard_case.spec.ts
  playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction.spec.ts
  playwright-e2e/test/contested/FR_giveAllocationDirections/give_allocation_direction_express_case.spec.ts
  playwright-e2e/test/contested/FR_manageCaseDocuments/manage_case_documents.spec.ts
  playwright-e2e/test/contested/FR_solicitorCreate/create_papercase.spec.ts
  playwright-e2e/test/contested/FR_updateContactDetails/update_contact_details.spec.ts
  playwright-e2e/test/contested/applicant_refuge_status_visibility.spec.ts
  playwright-e2e/test/contested/application_payment_submission.spec.ts
  playwright-e2e/test/contested/assign_respondent_case.spec.ts
  playwright-e2e/test/contested/createFlags/case_flag_tests.spec.ts
  playwright-e2e/test/preview/preview.spec.ts
  playwright-e2e/test/smoke/smoke.spec.ts
  test/functional/contested_events_test.js
  test/functional/pages/refund-case/refund-case.js
  test/functional/steps_file.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2652

#2665 Fix for nightly test failures
  Jenkinsfile_nightly
  playwright-e2e/data-utils/api/ApiHelper.ts
  playwright-e2e/data-utils/api/CaseAssignmentApi.ts
  playwright-e2e/data-utils/api/CcdApi.ts
  playwright-e2e/data-utils/api/TokenHelperApi.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/fixtures/fixtures.ts
  playwright-e2e/pages/events/create-case/DivorceDetailsPage.ts
  playwright-e2e/pages/events/create-case/MiamDetailsPage.ts
  playwright-e2e/pages/events/create-case/RespondentDetailsPage.ts
  playwright-e2e/pages/events/create-case/UploadOrderDocumentPage.ts
  playwright-e2e/pages/events/create-general-application/CreateGeneralApplicationPage.ts
  playwright-e2e/pages/events/list-for-hearing/ListForHearingPage.ts
  playwright-e2e/pages/events/list-for-interim-hearing/ListForInterimHearingPage.ts
  playwright-e2e/pages/events/manage-case-documents/ManageCaseDocumentsPage.ts
  playwright-e2e/pages/events/manage-hearings/ManageHearing.ts
  playwright-e2e/pages/events/upload-draft-orders/UploadDraftOrdersPage.ts
  playwright-e2e/pages/helpers/CommonActionsHelper.ts
  playwright-e2e/pages/helpers/enums/RadioEnums.ts
  playwright-e2e/resources/tab_content/consented/create_case_tabs.ts
  playwright-e2e/test/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts
  playwright-e2e/test/contested/applicant_refuge_status_visibility.spec.ts
  playwright-e2e/test/contested/assign_respondent_case.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2665

#2673 automerge after 7am and before 9am every weekday
  .github/renovate.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2673

#2620 DFR-3587 Confidentiality
  Jenkinsfile_nightly
  definitions/contested/json/AuthorisationCaseField/ManageHearings-nonprod.json
  definitions/contested/json/CaseField/ManageHearings-nonprod.json
  definitions/contested/json/CaseTypeTab/ManageHearings-nonprod.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/config/config.ts
  playwright-e2e/data-utils/DateHelper.ts
  playwright-e2e/data-utils/api/contested/ContestedEventApi.ts
  playwright-e2e/pages/CaseDetailsPage.ts
  playwright-e2e/pages/ManageCaseDashboardPage.ts
  playwright-e2e/pages/SigninPage.ts
  playwright-e2e/pages/components/case_file_view_tree.ts
  playwright-e2e/pages/events/manage-hearings/ManageHearing.ts
  playwright-e2e/pages/helpers/CommonActionsHelper.ts
  playwright-e2e/resources/check_your_answer_content/manage_hearings/manageHearingAddHearingTable.ts
  playwright-e2e/resources/payload/contested/caseworker/manage-barristers/add-applicant-barrister.json
  playwright-e2e/resources/payload/contested/caseworker/manage-barristers/add-respondent-barrister.json
  playwright-e2e/resources/payload/contested/caseworker/manage-interveners/add-applicant-intervener.json
  playwright-e2e/resources/payload/contested/caseworker/manage-interveners/add-respondent-intervener.json
  playwright-e2e/resources/tab_content/contested/manage-hearing_tabs.ts
  playwright-e2e/test/contested/FR_ManageHearings/manage_hearings.spec.ts
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2620, use-finrem-cos-pr-2358

#2684 Quick fix for nightly failures on expectation
  playwright-e2e/pages/CaseListPage.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2684

#2681 Dfr-3905 - PW Test - Send Order to an applicant solicitor
  playwright-e2e/config/case-data.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/events/create-general-application/CreateGeneralApplicationPage.ts
  playwright-e2e/pages/events/create-general-order/CreateGeneralOrderPage.ts
  playwright-e2e/pages/events/prepare-for-hearing/PrepareForHearingPage.ts
  playwright-e2e/pages/events/send-order/ContestedSendOrderPage.ts
  playwright-e2e/pages/events/update-contact-details/UpdateContactDetailsPage.ts
  playwright-e2e/resources/check_your_answer_content/send_order/sendOrderTable.ts
  playwright-e2e/test/contested/FR_SendOrderToApplicantSolicitor/send_order_applicant_solicitor.spec.ts
  test/functional/contested_events_test.js
  test/functional/steps_file.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2681

#2685 Fix Test failures on Nightly
  playwright-e2e/data-utils/DateHelper.ts
  playwright-e2e/pages/ManageCaseDashboardPage.ts
  playwright-e2e/pages/events/create-case/UploadOrderDocumentPage.ts
  playwright-e2e/pages/events/manage-hearings/ManageHearing.ts
  playwright-e2e/pages/helpers/CommonActionsHelper.ts
  playwright-e2e/test/consented/create_case.spec.ts
  playwright-e2e/test/contested/FR_ManageHearings/manage_hearings.spec.ts
  playwright-e2e/test/contested/restrict_upload_file_format.spec.ts
  test/functional/consented_test.js
  test/functional/contested_events_test.js
  test/functional/contested_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2685

#2686 Configure jenkins pipeline to configure build parameter
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2686

#2690 Fix pageId for FR_newPaperCase upload other document field
  definitions/contested/json/CaseEventToFields/CaseEventToFields-newPaperCase.json
  playwright-e2e/resources/check_your_answer_content/create_case/createCaseTable.ts
  playwright-e2e/test/contested/FR_CreateCases/create_express_papercase.spec.ts
  playwright-e2e/test/contested/FR_CreateCases/create_papercase.spec.ts
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2690

#2674 DFR 3782 Enable individual cover letters for uploaded draft orders - hamzah branch
  definitions/contested/json/AuthorisationComplexType/AuthorisationComplexType.json
  definitions/contested/json/CaseEventToComplexTypes/CaseEventToComplexTypes.json
  definitions/contested/json/ComplexTypes/ComplexTypes.json
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, use-finrem-cos-pr-2395, rel:finrem-ccd-definitions-pr-2674

#2699 Fix on-headers CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2699

#2704 Add new process order field to playwright test
  .gitignore
  package.json
  playwright-e2e/data-utils/PayloadMutator.ts
  playwright-e2e/data-utils/api/contested/ContestedEventApi.ts
  playwright-e2e/resources/files_built_by_tests/upload-draft-order/agreed-draft-order-document.docx
  playwright-e2e/test/contested/FR_directionOrder/process-order.spec.ts
  yarn.lock
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2704

#2679 DFR-3769-3772,3923,3928 Manage Hearing Migration
  definitions/contested/json/AuthorisationCaseEvent/ManageHearings-nonprod.json
  definitions/contested/json/AuthorisationCaseField/MhMigration-nonprod.json
  definitions/contested/json/CaseEvent/ManageHearings-nonprod.json
  definitions/contested/json/CaseEventToComplexTypes/ManageHearings-nonprod.json
  definitions/contested/json/CaseEventToFields/ManageHearings-nonprod.json
  definitions/contested/json/CaseField/MhMigrations-nonprod.json
  definitions/contested/json/CaseTypeTab/ManageHearings-nonprod.json
  definitions/contested/json/ComplexTypes/ManageHearings-nonprod.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/data-utils/api/contested/ContestedEventApi.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/BlankPage.ts
  playwright-e2e/pages/events/create-case/ChildrensDetailsPage.ts
  playwright-e2e/pages/events/general-application-directions/GeneralApplicationDirectionsPage.ts
  playwright-e2e/pages/events/list-for-hearing/ListForHearingPage.ts
  playwright-e2e/pages/events/manage-hearings/ManageHearing.ts
  playwright-e2e/pages/events/process-order/ProcessOrderPage.ts
  playwright-e2e/resources/tab_content/contested/hearings_tabs.ts
  playwright-e2e/test/contested/FR_GeneralApplicationDirections/general_application_directions.spec.ts
  playwright-e2e/test/contested/FR_addSchedulingListingInfo/list_for_hearing_shows_hearing_tab.spec.ts
  playwright-e2e/test/contested/FR_directionOrder/process-order.spec.ts
  playwright-e2e/test/contested/FR_listForInterimHearing/list_for_interim.hearing.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2679, use-finrem-cos-pr-2400

#2717 Dfr 3953 refactor parties on case logic to use its own object on the back end
  definitions/contested/json/ComplexTypes/ManageHearings-nonprod.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2717, use-finrem-cos-pr-2420

#2721 DFR-3950 Approved and Send Order
  playwright-e2e/config/case-data.ts
  playwright-e2e/data-utils/DateHelper.ts
  playwright-e2e/data-utils/api/contested/ContestedEventApi.ts
  playwright-e2e/data-utils/factory/contested/ContestedCaseFactory.ts
  playwright-e2e/pages/events/send-order/SendOrderPage.ts
  playwright-e2e/resources/check_your_answer_content/send_order/sendOrderTable.ts
  playwright-e2e/resources/payload/contested/caseworker/upload-draft-orders/agreed-draft-orders-applicant.json
  playwright-e2e/resources/tab_content/contested/send_order_tab.ts
  playwright-e2e/test/contested/FR_sendOrder/send_order.spec.ts
  test/functional/contested_test.js
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2721

#2719 DFR-3834 Make hearings tabe visible to judges
  definitions/contested/json/AuthorisationCaseField/ManageHearings-nonprod.json
  definitions/contested/json/CaseTypeTab/ManageHearings-nonprod.json
  playwright-e2e/config/case-data.ts
  playwright-e2e/data-utils/api/contested/ContestedEventApi.ts
  playwright-e2e/resources/payload/contested/caseworker/manage-hearing/add-a-hearing/add-a-hearing.json
  playwright-e2e/test/contested/FR_ManageHearings/manage_hearings.spec.ts
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-ccd-definitions-pr-2719

#2730 DFR-3961 - PW Test - Contested Case Creation For Ready For Hearing
  playwright-e2e/config/case-data.ts
  playwright-e2e/fixtures/create-fixture.ts
  playwright-e2e/pages/events/submit-uploaded-case-files/SubmitUploadedCaseFilesPage.ts
  playwright-e2e/resources/tab_content/contested/scheduling_and_listing_tab.ts
  playwright-e2e/test/contested/FR_submitUploadedCaseFiles/submit_uploaded_case_files.spec.ts
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ccd-definitions-pr-2730
